# Generated by Django 6.1.1 on 2026-09-25 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("meses_base", models.PositiveSmallIntegerField(default=0)),
                ("meses_bonificacion", models.PositiveSmallIntegerField(default=0)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Planes",
                "ordering": ["meses_base"],
            },
        ),
        migrations.CreateModel(
            name="Licencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo", models.CharField(db_index=True, max_length=30, unique=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ACTIVA", "Activa"),
                            ("BLOQUEADA", "Bloqueada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_activacion", models.DateTimeField(blank=True, null=True)),
                (
                    "fecha_vencimiento",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("observcacion", models.TextField(blank=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licencias",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licencias_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licencias",
                        to="licencias.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licencia",
                "verbose_name_plural": "Licencias",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Dispositivo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "installation_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("nombre_dispositivo", models.CharField(blank=True, max_length=150)),
                ("plataforma", models.CharField(blank=True, max_length=150)),
                ("version_app", models.CharField(blank=True, max_length=50)),
                ("activo", models.BooleanField(default=True)),
                ("primera_activacion", models.DateField(auto_now_add=True)),
                ("ultima_actividad", models.DateTimeField(blank=True, null=True)),
                (
                    "licencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispositivos",
                        to="licencias.licencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo",
                "verbose_name_plural": "Dispositivos",
                "ordering": ["-primera_activacion"],
            },
        ),
        migrations.CreateModel(
            name="Activacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("version_app", models.CharField(blank=True, max_length=50)),
                ("exitosa", models.BooleanField(default=True)),
                ("mensaje", models.CharField(blank=True, max_length=255)),
                (
                    "dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activaciones",
                        to="licencias.dispositivo",
                    ),
                ),
                (
                    "licencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activaciones",
                        to="licencias.licencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activacion",
                "verbose_name_plural": "activaciones",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Renovacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("vencimiento_anterior", models.DateTimeField()),
                ("nuevo_vencimiento", models.DateTimeField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="renovaciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "licencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="renovaciones",
                        to="licencias.licencia",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="renovaciones",
                        to="licencias.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Renovacion",
                "verbose_name_plural": "Renocaciones",
                "ordering": ["-fecha"],
            },
        ),
    ]
