# Generated by Django 6.1.1 on 2026-09-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0003_alter_plan_options_remove_plan_meses_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='creditos',
            field=models.PositiveSmallIntegerField(default=1, help_text='Cantidad de meses otorgados. 1 crédito equivale a 1 mes.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='creditos',
            field=models.PositiveSmallIntegerField(help_text='1 crédito equivale a 1 mes de licencia.'),
        ),
    ]
