# Generated by Django 6.1.1 on 2026-09-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0004_licencia_creditos_alter_plan_creditos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencia',
            name='plan',
        ),
        migrations.AddField(
            model_name='licencia',
            name='bonificacion',
            field=models.PositiveSmallIntegerField(default=0, help_text='Meses adicionales otorgados sin costo.'),
        ),
    ]
