# Generated by Django 6.1.1 on 2026-09-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0005_remove_licencia_plan_licencia_bonificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renovacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Renovación', 'verbose_name_plural': 'Renovaciones'},
        ),
        migrations.RemoveField(
            model_name='renovacion',
            name='plan',
        ),
        migrations.AddField(
            model_name='renovacion',
            name='bonificacion',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='renovacion',
            name='creditos',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='renovacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='renovacion',
            name='vencimiento_anterior',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
