# Generated by Django 6.1.1 on 2026-09-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("PERSONA", "Persona"), ("EMPRESA", "Empresa")],
                        default="EMPRESA",
                        max_length=20,
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("razon_social", models.CharField(blank=True, max_length=50)),
                ("nit_documento", models.CharField(blank=True, max_length=50)),
                ("telefono", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                ("observaciones", models.TextField(default=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nombre"],
            },
        ),
    ]
